routes/web.php
<?php
Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::resource('/employees', 'EmployeesController')->middleware('auth');

Route::prefix('pdf')->group(function () {
	Route::get('/list', 'EmployeesController@pdflist')->name('pdf.list');
    Route::get('/{id}', 'EmployeesController@pdfsingle')->name('pdf.single');
});

Route::prefix('excel')->group(function () {
	Route::get('/list', 'EmployeesController@excellist')->name('excel.list');
    Route::get('/{id}', 'EmployeesController@excelsingle')->name('excel.single');
});

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    public function employee() {
    	return $this->hasMany('App\Employee');
    }
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['name', 'email', 'department_id'];

    public function department() {
    	return $this->belongsTo('App\Department');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\EmployeeRequest;
use App\Employee;
use App\Department;
use Session;
use PDF;
use Excel;

class EmployeesController extends Controller
{
    public function index()
    {
        $employees = Employee::all()->sortByDesc('id');
        return view('employees.index')->withEmployees($employees);
    }

    public function create(Department $department)
    {
        return view('employees.create')->withDepartments($department->all());
    }

    public function store(EmployeeRequest $request)
    {
        if (Employee::create($request->all())) {
          return redirect()->route('employees.index')->with(Session::flash('success', 'O funcionário foi cadastrado com sucesso!'));
        }

        return redirect()->route('employees.index')->with(Session::flash('failed', 'Ocorreu algum erro ao tentar cadastrar o funcionário, tente novamente.'));
    }

    public function show(Employee $employee)
    {
        return view('employees.show')->withEmployee($employee);
    }

    public function edit(Employee $employee, Department $department)
    {
        return view('employees.edit')->with(['employee' => $employee, 'departments' => $department->all()]);
    }

    public function update(EmployeeRequest $request, Employee $employee)
    {
        if (Employee::where('id', $employee->id)->update(request()->except('_token', '_method'))) {
          return redirect()->route('employees.index')->with(Session::flash('success', 'O funcionário foi editado com sucesso!'));
        }

        return redirect()->route('employees.index')->with(Session::flash('failed', 'Ocorreu algum erro ao tentar editar o funcionário, tente novamente.'));
    }

    public function destroy(Employee $employee)
    {
        if ($employee->delete()) {
          return redirect()->route('employees.index')->with(Session::flash('success', 'O funcionário foi deletado com sucesso!'));
        }

        return redirect()->route('employees.index')->with(Session::flash('failed', 'Ocorreu algum erro ao tentar deletar o funcionário.'));
    }

    public function pdflist() {
        $pdf = PDF::loadView('employees.pdf.pdflist', ['employees' => Employee::all()->sortByDesc('id')]);
        return $pdf->stream();
    }

    public function pdfsingle($id) {
        $pdf = PDF::loadView('employees.pdf.pdfsingle', ['employee' => Employee::find($id)]);
        return $pdf->stream();
    }

    public function excellist() {
        $data = Employee::all()->sortByDesc('id');
        Excel::create('Employees', function($excel) use($data) { 
            $excel->sheet('EmployeeSheet', function($sheet) use($data) {
                $sheet->mergeCells('A1:B1');
                $sheet->cell('A1', function($cell) {
                     $cell->setValue('Funcionários');
                     $cell->setAlignment('center');
                     $cell->setFontWeight('bold');
                     $cell->setFontSize(18);
                });
                for($i = 2; $i < (4 * Employee::count()); $i++) {
                    for ($a = 0; $a < Employee::count(); $a++) {
                        $sheet->cell('A'.$i, function($cell) {
                            $cell->setValue('ID:');
                            $cell->setFontWeight('bold');
                        });
                        $sheet->cell('A'.($i+1), function($cell) {
                            $cell->setValue('Nome:');
                            $cell->setFontWeight('bold');
                        });
                        $sheet->cell('A'.($i+2), function($cell) {
                            $cell->setValue('Email:');
                            $cell->setFontWeight('bold');
                        });
                        $sheet->cell('A'.($i+3), function($cell) {
                            $cell->setValue('Departamento:');
                            $cell->setFontWeight('bold');
                        });
                        $sheet->cell('A'.($i+4), function($cell) {
                            $cell->setBackground('vbBlack');
                        });
                        $sheet->cell('B'.($i), function($cell) use($data, $i, $a) {
                            $cell->setValue($data[$a]->id);
                            $cell->setAlignment('justify');
                        });
                        $sheet->cell('B'.($i+1), function($cell) use($data, $i, $a) {
                            $cell->setValue($data[$a]->name);
                        });
                        $sheet->cell('B'.($i+2), function($cell) use($data, $i, $a) {
                            $cell->setValue($data[$a]->email);
                        });
                        $sheet->cell('B'.($i+3), function($cell) use($data, $i, $a) {
                            $cell->setValue($data[$a]->department['name']);
                        });
                        $sheet->cell('B'.($i+4), function($cell) {
                            $cell->setBackground('vbBlack');
                        });

                        $sheet->mergeCells('A'.($i+4).':B'.($i+4));
                        $i = $i + 5;
                    }
                    $a = 0;
                }
            });
        })->export('xlsx');
    }

    public function excelsingle($id) {
        $data = Employee::find($id);
        Excel::create('Employee', function($excel) use($data) { 
            $excel->sheet('EmployeeSheet', function($sheet) use($data) {
                $sheet->mergeCells('A1:B1');
                $sheet->cell('A1', function($cell) {
                     $cell->setValue('Funcionário');
                     $cell->setAlignment('center');
                     $cell->setFontWeight('bold');
                     $cell->setFontSize(18);
                });
                $sheet->cell('A2', function($cell) {
                    $cell->setValue('ID:');
                    $cell->setFontWeight('bold');
                });
                $sheet->cell('A3', function($cell) {
                    $cell->setValue('Nome:');
                    $cell->setFontWeight('bold');
                });
                $sheet->cell('A4', function($cell) {
                    $cell->setValue('Email:');
                    $cell->setFontWeight('bold');
                });
                $sheet->cell('A5', function($cell) {
                    $cell->setValue('Departamento:');
                    $cell->setFontWeight('bold');
                });
                $sheet->cell('B2', function($cell) use($data) {
                    $cell->setValue($data->id);
                    $cell->setAlignment('justify');
                });
                $sheet->cell('B3', function($cell) use($data) {
                    $cell->setValue($data->name);
                });
                $sheet->cell('B4', function($cell) use($data) {
                    $cell->setValue($data->email);
                });
                $sheet->cell('B5', function($cell) use($data) {
                    $cell->setValue($data->department['name']);
                });
            });
        })->export('xlsx');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Novo Funcionário</div>
                  <div class="panel-body">
                    @if($errors->any())
                      <div class="alert alert-danger">
                       @foreach ($errors->all() as $error)
                         * {{ $error }}<br>
                       @endforeach
                      </div>
                    @endif
                    <form action="{{ route('employees.store') }}" method="POST">
                      {!! csrf_field() !!}
                      <div class="form-group">
                        <label for="InputName">Nome</label>
                        <input class="form-control" type="text" name="name" value="{{ old('name') }}">
                      </div>
                      <div class="form-group">
                        <label for="InputEmail">Email</label>
                        <input class="form-control" type="text" name="email" value="{{ old('email') }}">
                      </div>
                      <label class="control-label">Departamento</label>
                        <div class="selectContainer" style="margin-bottom: 20px;">
                            <select class="form-control" name="department_id">
                                <option value="">Escolha um departamento</option>
                                @foreach ($departments as $department)
                                  <option value="{{ $department->id }}">{{ $department->name }}</option>
                                @endforeach
                            </select>
                        </div>
                      <button type="submit" class="btn btn-success btn-block">Cadastrar</button>
                      <a href="{{ route('employees.index') }}" class="btn btn-primary" style="margin-top: 10px;"><< Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Editar Funcionário</div>
                  <div class="panel-body">
                    @if($errors->any())
                      <div class="alert alert-danger">
                       @foreach ($errors->all() as $error)
                         * {{ $error }}<br>
                       @endforeach
                      </div>
                    @endif
                    <form action="{{ route('employees.update', $employee->id) }}" method="POST">
                      {!! csrf_field() !!}
                      <input type="hidden" name="_method" value="PUT">
                      <div class="form-group">
                        <label for="InputName">Nome</label>
                        <input class="form-control" type="text" name="name" value="{{ $employee->name }}">
                      </div>
                      <div class="form-group">
                        <label for="InputEmail">Email</label>
                        <input class="form-control" type="text" name="email" value="{{ $employee->email }}">
                      </div>
                      <label class="control-label">Departamento</label>
                        <div class="selectContainer" style="margin-bottom: 20px;">
                            <select class="form-control" name="department_id">
                                <option value="">Escolha um departamento</option>
                                @foreach ($departments as $department)
                                  <option value="{{ $department->id }}">{{ $department->name }}</option>
                                @endforeach
                            </select>
                        </div>
                      <button type="submit" class="btn btn-success btn-block">Editar</button>
                      <a href="{{ route('employees.index') }}" class="btn btn-primary" style="margin-top: 10px;"><< Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('styles')
  <link href="{{ asset('css/font-awesome-4.7.0/css/font-awesome.min.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Gerenciamento de Funcionários</div>
                  <div class="panel-body">
                    @if (Session::has('success'))
                      <div class="alert alert-success">{{ Session::get('success') }}</div>
                    @elseif (Session::has('failed'))
                      <div class="alert alert-danger">{{ Session::get('failed') }}</div>
                    @endif
                    <a href="{{ route('employees.create') }}" class="btn btn-success" style="float: right; margin-bottom: 15px;">Novo Funcionário</a>
                    <hr style="clear: both;">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Nome</th>
                          <th>Email</th>
                          <th>Departamento</th>
                          <th>Ação</th>
                          <th>#</th>
                        </tr>
                      </thead>
                      <tbody>
                          @foreach ($employees as $employee)
                            <tr>
                              <th scope="row">{{ $employee->id }}</th>
                              <td>{{ $employee->name }}</td>
                              <td>{{ $employee->email }}</td>
                              <td>{{ $employee->department['name'] }}</td>
                              <td>
                                <a href="{{ route('employees.show', $employee->id) }}" title="Visualizar"><i class="fa fa-eye" aria-hidden="true" style="font-size: 22px; color: blue;"></i></a>
                                <a href="{{ route('employees.edit', $employee->id) }}" title="Editar"><i class="fa fa-pencil" aria-hidden="true" style="font-size: 22px; color: black; margin-left: 5px;"></i></a>
                                <form style="display: inline-block;" action="{{ route('employees.destroy', $employee->id) }}" method="POST">
                                   {{ csrf_field() }}
                                   <input type="hidden" name="_method" value="DELETE">
                                   <button type="submit" style="background: none; border: none;"><i title="Excluir" class="fa fa-trash" aria-hidden="true" style="font-size: 22px;"></i></a>
                                </form>
                              </td>
                              <td>
                                <a href="{{ route('pdf.single', $employee->id) }}" target="_blank" title="PDF"><i class="fa fa-file-pdf-o" aria-hidden="true" style="font-size: 22px;"></i></a>
                                <a href="{{ route('excel.single', $employee->id) }}" title="Excel"><i class="fa fa-table" aria-hidden="true" style="margin-left: 5px; font-size: 22px; color: green;"></i></a>
                              </td>
                            </tr>
                          @endforeach
                      </tbody>
                    </table>
                    <div style="float: right;">
                      Lista PDF: <a href="{{ route('pdf.list') }}" target="_blank" title="PDF"><i class="fa fa-file-pdf-o" aria-hidden="true" style="font-size: 20px;"></i></a><br>
                      Lista Excel: <a href="{{ route('excel.list') }}" title="Excel"><i class="fa fa-table" aria-hidden="true" style="font-size: 20px; color: green;"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/pdf/pdflist.blade.php
<h1>Lista de Funcionários</h1>
@foreach ($employees as $employee)
	<b>ID:</b> {{ $employee->id }}<br>
	<b>Nome:</b> {{ $employee->name }}<br>
	<b>Email:</b> {{ $employee->email }}<br>
	<b>Departamento:</b> {{ $employee->department['name'] }}
	<br><br>
@endforeach

resources/views/employees/pdf/pdfsingle.blade.php
<h1>Funcionário, {{ $employee->name }}.</h1>

<b>ID:</b> {{ $employee->id }}<br>
<b>Email:</b> {{ $employee->email }}<br>
<b>Departamento:</b> {{ $employee->department['name'] }}

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('styles')
  <link href="{{ asset('css/font-awesome-4.7.0/css/font-awesome.min.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Informações do Funcionário</div>
                  <div class="panel-body">
                    PDF: <a href="{{ route('pdf.single', $employee->id) }}" target="_blank" title="PDF"><i class="fa fa-file-pdf-o" aria-hidden="true" style="font-size: 22px;"></i></a><br>
                    Excel: <a href="{{ route('excel.single', $employee->id) }}" title="Excel"><i class="fa fa-table" aria-hidden="true" style="font-size: 22px; color: green;"></i></a>
                    <table class="table table-striped" style="margin-top: 20px;">
                      <tbody>
                          <tr>
                            <th>ID:</th>
                            <td>{{ $employee->id }}</td>
                          </tr>
                          <tr>
                            <th>Nome:</th>
                            <td>{{ $employee->name }}</td>
                          </tr>
                          <tr>
                            <th>Email:</th>
                            <td>{{ $employee->email }}</td>
                          </tr>
                          <tr>
                            <th>Departamento:</th>
                            <td>{{ $employee->department['name'] }}</td>
                          </tr>
                      </tbody>
                    </table>
                    <a href="{{ route('employees.index') }}" class="btn btn-primary"><< Voltar</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Página Inicial</div>
                    <div class="panel-body">
                        Bem Vindo!
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('styles')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{{ route('employees.index') }}">Gerenciamento de Funcionários</a></li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Sair
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>